config/routes.rb
# https://github.com/paweljw/bookstore-backend/blob/part-3/config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :animals do
    get "delete"
  end
  root to: "animals#index"

  resources :zones do
    get "delete"
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  namespace :api do
    resources :animals
    resources :zones
  end
end

app/models/animal.rb
class Animal < ApplicationRecord
  has_many :users
  belongs_to :zone

  validates :name, presence: true
  validates :breed, presence: true
  validates :year_birth, numericality: { only_integer: true }

  mount_uploader :animal_photo, AnimalPhotoUploader
  # Animal photo validation
  validates_integrity_of :animal_photo
  validates_processing_of :animal_photo
  validates :animal_photo, file_size: { less_than: 5.megabytes }

  def self.search(search)
    if search
      where('name LIKE ?', "%#{search}%")
    else
      all
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  belongs_to :animal
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/zone.rb
class Zone < ApplicationRecord
  has_one :animal

  validates :name, presence: true
  validates :weather, presence: true
  validates :temperature, presence: true, numericality: true, :inclusion => -20..60
  validates :humidity, presence: true, numericality: true, :inclusion => 10..100
end

app/controllers/animals_controller.rb
# http://railscasts.com/episodes/240-search-sort-paginate-with-ajax?autoplay=true

class AnimalsController < ApplicationController
  before_action :set_animal, only: [:show, :edit, :update, :destroy]

  # GET /animals
  # GET /animals.json
  def index
    @animals = Animal.search(params[:search])
  end

  # GET /animals/1
  # GET /animals/1.json
  def show
    @animal = Animal.find(params[:id])
  end

  # GET /animals/new
  def new
    @animal = Animal.new
  end

  # GET /animals/1/edit
  def edit
    @animal = Animal.find(params[:id])
  end

  # POST /animals
  # POST /animals.json
  def create
    @animal = Animal.all
    @animal = Animal.create(animal_params)
    # @animal.zone = Zone.find_by_name(@animal.zone)

    respond_to do |format|
      if @animal.save
        format.html { redirect_to @animal, notice: 'Animal was successfully created.' }
        format.json { render :show, status: :created, location: @animal }
      else
        format.html { render :new }
        format.json { render json: @animal.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /animals/1
# PATCH/PUT /animals/1.json
  def update
    @animals = Animal.all
    @animal = Animal.find(params[:id])

    @animal.update_attributes(animal_params)

    respond_to do |format|
      if @animal.update(animal_params)
        format.html { redirect_to @animal, notice: 'Animal was successfully updated.' }
        format.json { render :show, status: :ok, location: @animal }
      else
        format.html { render :edit }
        format.json { render json: @animal.errors, status: :unprocessable_entity }
      end
    end
  end

  def delete
    @animal = Animal.find(params[:animal_id])
  end

  # DELETE /animals/1
  # DELETE /animals/1.json
  def destroy
    @animals = Animal.all
    @animal = Animal.find(params[:id])
    @animal.destroy
    respond_to do |format|
      format.html { redirect_to animals_url, notice: 'Animal was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_animal
      @animal = Animal.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def animal_params
      params.require(:animal).permit(:name, :animal_photo, :animal_photo_cache, :zone_id, :breed, :zone, :year_birth)
    end
end

app/controllers/api/animals_controller.rb
class Api::AnimalsController < ApplicationController
  def index
    @animals = Animal.all
    render json: @animals
  end
end

app/controllers/api/zones_controller.rb
class Api::ZonesController < ApplicationController
  def index
    @zones = Zone.all
    render json: @zones
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  before_action :authenticate_user!

  before_action :configure_permitted_parameters, if: :devise_controller?
protected
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up) do |u|
      u.permit(:username, :email, :password, :password_confirmation, :remember_me, :animal_photo, :animal_photo_cache)
    end
    devise_parameter_sanitizer.permit(:account_update) do |u|
      u.permit(:username, :password, :password_confirmation, :current_password, :animal_photo, :animal_photo_cache, :remove_animal_photo)
    end
  end
  
end

app/controllers/zones_controller.rb
class ZonesController < ApplicationController
  before_action :set_zone, only: [:show, :edit, :update, :destroy]

  # GET /zones
  # GET /zones.json
  def index
    @zones = Zone.all
  end

  # GET /zones/1
  # GET /zones/1.json
  def show
    @zone = Zone.find(params[:id])
  end

  # GET /zones/new
  def new
    @zone = Zone.new
  end

  # GET /zones/1/edit
  def edit
    @zone = Zone.find(params[:id])
  end

  # POST /zones
  # POST /zones.json
  def create
    @zones = Zone.all
    @zone = Zone.new(zone_params)

    respond_to do |format|
      if @zone.save
        format.html { redirect_to @zone, notice: 'Zone was successfully created.' }
        format.json { render :show, status: :created, location: @zone }
      else
        format.html { render :new }
        format.json { render json: @zone.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /zones/1
  # PATCH/PUT /zones/1.json
  def update
    @zones = Zone.all
    @zone = Zone.find(params[:id])

    @zone.update_attributes(zone_params)

    respond_to do |format|
      if @zone.update(zone_params)
        format.html { redirect_to @zone, notice: 'Zone was successfully updated.' }
        format.json { render :show, status: :ok, location: @zone }
      else
        format.html { render :edit }
        format.json { render json: @zone.errors, status: :unprocessable_entity }
      end
    end
  end

  def delete
    @zone = Zone.find(params[:zone_id])
  end

  # DELETE /zones/1
  # DELETE /zones/1.json
  def destroy
    @zones = Zone.all
    @zone = Zone.find(params[:id])
    @zone.destroy
    respond_to do |format|
      format.html { redirect_to zones_url, notice: 'Zone was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_zone
      @zone = Zone.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def zone_params
      params.require(:zone).permit(:name, :weather, :temperature, :humidity)
    end
end

app/helpers/animals_helper.rb
module AnimalsHelper
end

app/helpers/api/animals_helper.rb
module Api::AnimalsHelper
end

app/helpers/api/zones_helper.rb
module Api::ZonesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/zones_helper.rb
module ZonesHelper
end

app/views/animals/_delete.html.erb
<div class="modal-dialog">
  <div class="modal-content">
  <div class="modal-header">
    <h3>Borrar Animal</h3>
  </div>
  <div class="modal-body">
  <ul class="errors"></ul>
  Segur que vols eliminar <b><%= @animal.name %></b>?
  </div>
  <div class="modal-footer">
    <%= link_to "Si, elimina aquest animal", animal_path(@animal), method: :delete, remote: true, class: "btn btn-danger" %>
    <%= link_to "No, no l'eliminis", "#", class: "btn btn-default", data: { dismiss: "modal" } %>
  </div>
  </div>
</div>

app/views/animals/_edit.html.erb
<div class="modal-header">
  <h3><%= "Editando #{@animal.name}" %></h3>
</div>
<%= render "form" %>

app/views/animals/_form.html.erb
<div class="modal-dialog">
  <div class="modal-content">

    <%= form_for @animal, remote: true, html: { style: "display:inline;" } do |form| %>
      <div class="modal-body">
      <ul class="errors"></ul>

      <% if @animal.animal_photo.present? %>

        <%= image_tag(@animal.animal_photo.url, height: 200) %>

        <div class="form-group">

          <%= form.label :remove_animal_photo, style: "display: inline" %>

          <%= form.check_box :remove_animal_photo %>

        </div>

      <% end %>
      
      <div class="form-group">
        <%= form.file_field :animal_photo %>

        <%= form.hidden_field :animal_photo_cache %>
      </div>


      <div class="form-group">
        <%= form.label :name, class:"control-label" %>
        <%= form.text_field :name, class: "form-control" %>
      </div>

      <div class="form-group">
        <%= form.label :breed %>
        <%= form.text_field :breed, class: "form-control" %>
      </div>

      <div class="form-group">
        <%= form.collection_select :zone_id, Zone.all, :id, :name, :prompt => "Select a zone", class: "form-control" %>
      </div>

      <div class="form-group">
        <%= form.label :year_birth %>
        <%= form.number_field :year_birth, class: "form-control" %>
      </div>

      <div class="actions">
        <%= form.submit class: "btn btn-primary" %>
      </div>

      </div>
    <% end %>

  </div>
</div>

app/views/animals/_index.html.erb
    <% @animals.each do |animal| %>
      <tr>
        <td><img src="<%= animal.animal_photo.url %>", height="200"></td> 
        <td><%= animal.name %></td>
        <td><%= animal.breed %></td>
        <td><%= animal.zone.name %></td>
        <td><%= animal.year_birth %></td>
        <td><%= link_to 'Show', animal, class: "btn btn-default" %></td>
        <td><%= link_to 'Edit', edit_animal_path(animal), remote: true, class: "btn btn-primary" %></td>
        <td><%= link_to 'Delete', animal_delete_path(animal), remote: true, class: "btn btn-danger" %></td>
      </tr>
    <% end %>

app/views/animals/_new.html.erb
<div class="modal-header">
  <h3>Nuevo Animal</h3>
</div>
<%= render "form" %>

app/views/animals/_save.js.erb
$("ul.errors").html("")
<% if @animal.errors.any? %>
  <% @animal.errors.full_messages.each do |message| %>
    $("ul.errors").append($("<li />").html("<%= message.html_safe %>"))
  <% end %>
<% else %>
  $(".animal-index").html("<%= escape_javascript(render 'index') %>")
  $("#animal-modal").modal("hide")
<% end %>

app/views/animals/delete.js.erb
$("#animal-modal").html("<%= escape_javascript(render 'delete') %>")
$("#animal-modal").modal("show")

app/views/animals/edit.html.erb
<h1>Editing Animal</h1>

<%= render 'form', animal: @animal %>

<%= link_to 'Show', @animal %> |
<%= link_to 'Back', animals_path %>

app/views/animals/edit.js.erb
$("#animal-modal").html("<%= escape_javascript(render 'edit') %>")
$("#animal-modal").modal("show")

app/views/animals/index.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Nuevo Animal', new_animal_path, remote: true, class: "btn btn-success create-new" %>

<h1>Animals</h1>

<%= form_tag animals_path, :method => 'get', :id => "animals_search", class: "form-inline" do %>
  <p>
    <%= text_field_tag :search, params[:search], class: "form-control" %>
    <%= submit_tag "Search", :name => nil, class: "btn btn-primary" %>
  </p>
<% end %>

<br>
<table>
  <thead>
    <tr>
      <th></th>
      <th>Name</th>
      <th>Breed</th>
      <th>Zone</th>
      <th>Year birth</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody id="animals-table">
    <%= render 'index' %>
  </tbody>
</table>

<div id="animal-modal" class="modal fade"></div>

app/views/animals/index.js.erb
$("#animals-table").html("<%= escape_javascript(render("index")) %>")

app/views/animals/new.html.erb
<h1>New Animal</h1>

<%= render 'form', animal: @animal %>

<%= link_to 'Back', animals_path %>

app/views/animals/new.js.erb
$("#animal-modal").html("<%= escape_javascript(render 'new') %>")
$("#animal-modal").modal("show")

app/views/animals/show.html.erb
<p id="notice"><%= notice %></p>

<p>
<img src="<%= @animal.animal_photo.url %>", height="200">
</p>

<p>
  <strong>Name:</strong>
  <%= @animal.name %>
</p>

<p>
  <strong>Breed:</strong>
  <%= @animal.breed %>
</p>

<p>
  <strong>Zone:</strong>
  <%= @animal.zone.name %>
</p>

<p>
  <strong>Year birth:</strong>
  <%= @animal.year_birth %>
</p>

<%= link_to 'Edit', edit_animal_path(@animal) %> |
<%= link_to 'Back', animals_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "ZooRails" %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.2/html5shiv.min.js" type="text/javascript"></script>
    <![endif]-->
  </head>
  <body>

    <div class="navbar navbar-default navbar-static-top">
      <div class="container">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="#">ZooRails</a>
      </div>
    </div>

    <div class="container">
      <div class="row">
        <div class="col-lg-9">
          <%= yield %>
        </div>
        <div class="col-lg-3">
          <div class="well sidebar-nav">
          <ul class="nav nav-list">
          <li class="nav-header">Rutas</li>
          <li><%= link_to "/animals", "/animals"  %></li>
          <li><%= link_to "/zones", "/zones"  %></li>
        </ul>
        <ul class="nav nav-list">
              <li class="nav-header">API</li>
              <li><%= link_to "/api/animals", "/api/animals", target: :_blank %></li>
              <li><%= link_to "/api/zones", "/api/zones", target: :_blank %></li>
            </ul>
          </div><!--/.well -->
        </div><!--/span-->
      </div><!--/row-->

      <footer>
        
      </footer>

    </div> <!-- /container -->

  </body>
</html>

app/views/zones/_delete.html.erb
<div class="modal-dialog">
  <div class="modal-content">
  <div class="modal-header">
    <h3>Delete Zone</h3>
  </div>
  <div class="modal-body">
  <ul class="errors"></ul>
  Segur que vols eliminar <b><%= @zone.name %></b>?
  </div>
  <div class="modal-footer">
    <%= link_to "Si, borra aquesta zona", zone_path(@zone), method: :delete, remote: true, class: "btn btn-danger" %>
    <%= link_to "No, no la borris", "#", class: "btn btn-default", data: { dismiss: "modal" } %>
  </div>
  </div>
</div>

app/views/zones/_edit.html.erb
<div class="modal-header">
  <h3><%= "Editando #{@zone.name}" %></h3>
</div>
<%= render "form" %>

app/views/zones/_form.html.erb
<div class="modal-dialog">
  <div class="modal-content">

<%= form_for @zone, remote: true, html: { style: "display:inline;" } do |form| %>
  <div class="modal-body">
    <ul class="errors"></ul>

    <div class="form-group">
      <%= form.label :name, class: "control-label" %>
      <%= form.text_field :name, class: "form-control" %>
    </div>

    <div class="form-group">
      <%= form.label :weather, class: "control-label" %>
      <%= form.text_field :weather, class: "form-control" %>
    </div>

    <div class="form-group">
      <%= form.label :temperature, class: "control-label" %>
      <%= form.number_field :temperature, class: "form-control" %>
    </div>

    <div class="form-group">
      <%= form.label :humidity, class: "control-label" %>
      <%= form.number_field :humidity, class: "form-control" %>
    </div>

    <div class="actions">
      <%= form.submit class: "btn btn-primary" %>
    </div>
  </div>
<% end %>
</div>
</div>

app/views/zones/_index.html.erb
<% @zones.each do |zone| %>
  <tr>
    <td><%= zone.name %></td>
    <td><%= zone.weather %></td>
    <td><%= zone.temperature %></td>
    <td><%= zone.humidity %></td>
    <td><%= link_to 'Show', zone, class: "btn btn-default" %></td>
    <td><%= link_to 'Edit', edit_zone_path(zone), remote: true, class: "btn btn-primary" %></td>
    <td><%= link_to "Delete", zone_delete_path(zone), remote: true, class: "btn btn-danger" %></td>
  </tr>
<% end %>

app/views/zones/_new.html.erb
<div class="modal-header">
<h3>New Zone</h3>
</div>
<%= render "form" %>

app/views/zones/_save.js.erb
$("ul.errors").html("")
<% if @zone.errors.any? %>
  <% @zone.errors.full_messages.each do |message| %>
    $("ul.errors").append($("<li />").html("<%= message.html_safe %>"))
  <% end %>
<% else %>
  $(".zone-index").html("<%= escape_javascript(render 'index') %>")
  $("#zone-modal").modal("hide")
<% end %>

app/views/zones/create.js.erb
<%= render "save" %>

app/views/zones/delete.js.erb
$("#zone-modal").html("<%= escape_javascript(render 'delete') %>")
$("#zone-modal").modal("show")

app/views/zones/destroy.js.erb
<%= render "save" %>

app/views/zones/edit.html.erb
<h1>Editing Zone</h1>

<%= render 'form', zone: @zone %>

<%= link_to 'Show', @zone %> |
<%= link_to 'Back', zones_path %>

app/views/zones/edit.js.erb
$("#zone-modal").html("<%= escape_javascript(render 'edit') %>")
$("#zone-modal").modal("show")

app/views/zones/new.html.erb
<h1>New Zone</h1>

<%= render 'form', zone: @zone %>

<%= link_to 'Back', zones_path %>

app/views/zones/new.js.erb
$("#zone-modal").html("<%= escape_javascript(render 'new') %>")
$("#zone-modal").modal("show")

app/views/zones/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @zone.name %>
</p>

<p>
  <strong>Weather:</strong>
  <%= @zone.weather %>
</p>

<p>
  <strong>Temperature:</strong>
  <%= @zone.temperature %>
</p>

<p>
  <strong>Humidity:</strong>
  <%= @zone.humidity %>
</p>

<%= link_to 'Edit', edit_zone_path(@zone) %> |
<%= link_to 'Back', zones_path %>